//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Image
    {
        public int PostImage_Id { get; set; }
        public int Post_Id { get; set; }
        public string ImageLocation { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
