//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Exchange_Information = new HashSet<Exchange_Information>();
            this.Post_Comment = new HashSet<Post_Comment>();
            this.Post_Image = new HashSet<Post_Image>();
        }
    
        public int Post_Id { get; set; }
        public int User_Id { get; set; }
        public string Book_Name { get; set; }
        public string Writter_Name { get; set; }
        public int Catagory_Id { get; set; }
        public int Book_Quantity { get; set; }
        public string Address { get; set; }
        public System.DateTime Publish_Date { get; set; }
        public bool Exchange { get; set; }
        public bool Parmanent_Exchange { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Information> Exchange_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Comment> Post_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Image> Post_Image { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
