//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Block
    {
        public int Block_Id { get; set; }
        public int User_Id_Victim { get; set; }
        public int User_Id_From { get; set; }
        public string Block_Reasion { get; set; }
        public System.DateTime Makedate { get; set; }
    
        public virtual User_Information User_Information { get; set; }
        public virtual User_Information User_Information1 { get; set; }
    }
}
