//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Information()
        {
            this.Exchange_Information = new HashSet<Exchange_Information>();
            this.Exchange_Information1 = new HashSet<Exchange_Information>();
            this.Posts = new HashSet<Post>();
            this.Post_Comment = new HashSet<Post_Comment>();
            this.Post_Comment1 = new HashSet<Post_Comment>();
            this.Reviews = new HashSet<Review>();
            this.Reviews1 = new HashSet<Review>();
            this.User_Block = new HashSet<User_Block>();
            this.User_Block1 = new HashSet<User_Block>();
        }
    
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Contact { get; set; }
        public bool User_Status { get; set; }
        public int Division_Id { get; set; }
        public int ZIla_Id { get; set; }
        public string Address { get; set; }
        public Nullable<int> School_Id { get; set; }
        public Nullable<int> College_Id { get; set; }
        public Nullable<int> University_Id { get; set; }
        public string User_Image { get; set; }
        public int Registration_Id { get; set; }
    
        public virtual College College { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Information> Exchange_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Information> Exchange_Information1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Comment> Post_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Comment> Post_Comment1 { get; set; }
        public virtual Registration Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews1 { get; set; }
        public virtual School School { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Block> User_Block { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Block> User_Block1 { get; set; }
        public virtual Zila Zila { get; set; }
    }
}
